# Generated by Django 5.0.3 on 2024-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
