# Generated by Django 5.0.3 on 2024-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0002_tools_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='in_job',
            field=models.BooleanField(default=False, verbose_name='W pracy'),
        ),
        migrations.AddField(
            model_name='tools',
            name='in_service',
            field=models.BooleanField(default=False, verbose_name='W serwisie'),
        ),
    ]
