# Generated by Django 5.0.3 on 2024-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0003_tools_in_job_tools_in_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, verbose_name='Nazwa zlecenia')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
            ],
        ),
    ]
