# Generated by Django 5.0.3 on 2024-04-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='model',
        ),
    ]
