# Generated by Django 5.0.3 on 2024-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0007_service_repaired'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Ilość w serwisie'),
        ),
    ]
