# Generated by Django 5.0.3 on 2024-04-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0008_service_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ilość')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_workshop.jobs')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_workshop.tools')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='tools',
            field=models.ManyToManyField(through='virtual_workshop.JobTool', to='virtual_workshop.tools', verbose_name='Narzędzia'),
        ),
    ]
