# Generated by Django 5.0.3 on 2024-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0009_jobtool_jobs_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtool',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywne'),
        ),
    ]
