# Generated by Django 5.0.3 on 2024-04-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_workshop', '0012_createuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
